// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fmg0KH4I-WgIjEjkAKgKSMI8JFDVUKI',
    appId: '1:734274838313:web:3fc432284e682cf81aa138',
    messagingSenderId: '734274838313',
    projectId: 'length-factory',
    authDomain: 'length-factory.firebaseapp.com',
    storageBucket: 'length-factory.firebasestorage.app',
    measurementId: 'G-ML2HTDDCX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrs1jXJ-rHSvK8SfJSmasBgkJVf_JlLwc',
    appId: '1:734274838313:android:322049ae033cb82a1aa138',
    messagingSenderId: '734274838313',
    projectId: 'length-factory',
    storageBucket: 'length-factory.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2fmg0KH4I-WgIjEjkAKgKSMI8JFDVUKI',
    appId: '1:734274838313:web:e2b5d71bdd46fc1f1aa138',
    messagingSenderId: '734274838313',
    projectId: 'length-factory',
    authDomain: 'length-factory.firebaseapp.com',
    storageBucket: 'length-factory.firebasestorage.app',
    measurementId: 'G-QE1CGVWJX3',
  );
}
